[package]
edition = "2021"
name = "aw-ascii85"
version = "0.1.0"
license = "MIT"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
harness = false
name = "benchmarks"

[lib]
bench = false
