stages:
- test

clippy:
  image: rustlang/rust:nightly-slim
  stage: test
  timeout: 1 hours
  script:
    - rustup component add clippy --toolchain nightly
    - cargo clippy --all-features --all-targets -- -D warnings

fmt:
  image: rustlang/rust:nightly-slim
  stage: test
  timeout: 1 hours
  script:
    - rustup component add rustfmt --toolchain nightly
    - cargo +nightly fmt -- --check

test:
  image: rust:slim
  stage: test
  timeout: 1 hours
  script:
    - cargo test
